# Generated by Django 2.0.3 on 2018-03-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='twit',
            field=models.TextField(null=True),
        ),
    ]
