# Generated by Django 2.0.3 on 2018-03-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0002_twit_twit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twit',
            name='location',
        ),
        migrations.AddField(
            model_name='twit',
            name='latitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twit',
            name='longitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
