# Generated by Django 2.0.3 on 2018-03-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0003_auto_20180317_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='twit',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
